name: Java Maven Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build the project with Maven
    - name: Build with Maven
      working-directory: ProgPOE   # <-- update this if pom.xml is elsewhere
      run: mvn clean compile

    # Step 4: Run all tests
    - name: Run Maven Tests
      working-directory: ProgPOE   # <-- same folder as pom.xml
      run: mvn test
